### ISSUE TITLE
multiprocessing deadlock in yam correlation  

### ISSUE THREAD

**Issue by WeijunW** [trichter/yam#2]
When running "yam-runtests -v" in multi-core(cpu) machine, program deadlock when testing "yam correlation 1".   Trackback information shows it is relative with hdf5 file writing in start_correlate function of yam/commands.py .  Similar problem appear for other data when doing correlation. 
When running in single core, i.e. yam-runtests -n 1 -v or yam correlation 1 -n 1, everything goes well. 
The running enviroments:
Centos 7.4
python 3.6.1-3..6.4
obspy 1.1.0
obspyh5 0.3.2
h5py 2.7/2.7.1
yam 0.3.1.dev0

**Comment by trichter** [comment]
Thank you for reporting this issue.

Unfortunately I was not yet able to reproduce this bug. 

I post the two tracebacks you sent by mail.

Are you still seeing the second traceback with up to date packages?

Can you do another experiment: In a fresh directory run this script
```py
from h5py import File
with File('corr.h5') as f:
    pass
```

which creates the empty HDF5 file. Afterwards run the correlate command. Does it change anything?




Traceback 1:
```
>
>
> (obspy) [wwj@t570 yam_test]$ yam-runtests -v

...

>> yam correlate 1 -vvv
> CLI tests passed:  35%|██████████████████████████████████████████████████████▊                                                                                                     | 26/74 [00:20<00:19,  2.43it/s]
> ***CTRL+C here***
>
> CLI tests passed:  36%|████████████████████████████████████████████████████████▉                                                                                                   | 27/74 [03:48<17:41, 22.58s/it]Traceback (most recent call last):
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/multiprocessing/pool.py", line 684, in next
>      item = self._items.popleft()
> IndexError: pop from an empty deque
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>    File "/home/wwj/anaconda3/envs/obspy/bin/yam-runtests", line 11, in <module>
>      load_entry_point('yam', 'console_scripts', 'yam-runtests')()
>    File "/home/wwj/old/gits/obspy/yam/yam/tests/__init__.py", line 27, in run
>      ret = not runner.run(suite).wasSuccessful()
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/unittest/runner.py", line 176, in run
>      test(result)
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/unittest/suite.py", line 84, in __call__
>      return self.run(*args, **kwds)
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/unittest/suite.py", line 122, in run
>      test(result)
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/unittest/suite.py", line 84, in __call__
>      return self.run(*args, **kwds)
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/unittest/suite.py", line 122, in run
>      test(result)
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/unittest/suite.py", line 84, in __call__
>      return self.run(*args, **kwds)
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/unittest/suite.py", line 122, in run
>      test(result)
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/unittest/case.py", line 649, in __call__
>      return self.run(*args, **kwds)
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/unittest/case.py", line 601, in run
>      testMethod()
>    File "/home/wwj/old/gits/obspy/yam/yam/tests/test_main.py", line 168, in test_cli
>      self.out('correlate 1')  # takes long
>    File "/home/wwj/old/gits/obspy/yam/yam/tests/test_main.py", line 82, in out
>      self.script(cmd.split())
>    File "/home/wwj/old/gits/obspy/yam/yam/main.py", line 388, in run_cmdline
>      run(**args)
>    File "/home/wwj/old/gits/obspy/yam/yam/main.py", line 147, in run
>      run2(command, **args)
>    File "/home/wwj/old/gits/obspy/yam/yam/main.py", line 211, in run2
>      yam.commands.start_correlate(io, **args)
>    File "/home/wwj/old/gits/obspy/yam/yam/commands.py", line 167, in start_correlate
>      total=len(tasks)):
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/site-packages/tqdm/_tqdm.py", line 959, in __iter__
>      for obj in iterable:
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/multiprocessing/pool.py", line 688, in next
>      self._cond.wait(timeout)
>    File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/threading.py", line 295, in wait
>      waiter.acquire()
> KeyboardInterrupt 
```


Traceback 2:
```
$ yam correlate 1b

--------------------error message--------------------------------
 20%|████████▌                                 | 75/366 [02:52<11:08, 2.30s/it]Traceback (most recent call last):
  File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/site-packages/h5py/_hl/files.py", line 111, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wwj/anaconda3/envs/obspy/bin/yam", line 11, in <module>
    load_entry_point('yam', 'console_scripts', 'yam')()
  File "/home/wwj/old/gits/obspy/yam/yam/main.py", line 388, in run_cmdline
    run(**args)
  File "/home/wwj/old/gits/obspy/yam/yam/main.py", line 147, in run
    run2(command, **args)
  File "/home/wwj/old/gits/obspy/yam/yam/main.py", line 211, in run2
    yam.commands.start_correlate(io, **args)
  File "/home/wwj/old/gits/obspy/yam/yam/commands.py", line 168, in start_correlate
    _write_stream(result)
  File "/home/wwj/old/gits/obspy/yam/yam/commands.py", line 156, in _write_stream
    result[key].write(io[key], 'H5', mode='a')
  File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/stream.py", line 1443, in write
    write_format(self, filename, **kwargs)
  File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/site-packages/obspyh5.py", line 186, in writeh5
    with h5py.File(fname, mode, libver='latest') as f:
  File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/wwj/anaconda3/envs/obspy/lib/python3.6/site-packages/h5py/_hl/files.py", line 113, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'corr.h5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2) 
```

**Comment by WeijunW** [comment]
1. Creating empty h5 file before correlation doesn't avoid the bug. 
2. After updated python and h5py, bugs still appear for track1 and track2.
3. setting  "parallel_inner_loop":true in conf.json  work fine, so pool.map() works  fine, 
and it looks like both bugs are  connecting with  ：
       for result in tqdm.tqdm(pool.imap_unordered(do_work, tasks)
                                total=len(tasks)):
in start_correlate function. 
As you can't repeat the bugs, they are possible platform dependent.

**Comment by trichter** [comment]
Thanks for the feedback. Point 3 is reassuring.

The hdf5 writing issue is puzzling, because it is not done parallel.

Another idea: Could you edit the yam/commands.py file in your anaconda distribution and try out
`pool.imap` or `pool.map` instead of `pool.imap_unordered`?

**Comment by trichter** [comment]
I tried `yam-runtests` on a machine with CentOS 7, but everything is working as expected. Still I was not able to reproduce this bug.

**Comment by WeijunW** [comment]
Hi, trichter,
Sorry didn't response for a long time. Actually multiprocess problems still trouble me in different computers I can acess, and I also found similar problems when running msnoise. Recently I tested it with python3.7 in a Mac computer, and found it worked well with multi-processor. It likes like I should try  changing python version and close this issue. Thanks.
